services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: db_nodejs14
      MYSQL_USER: user
      MYSQL_PASSWORD: "12345"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_interval: 5s

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8020:80"
    networks:
      - net-mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_interval: 5s

  redis-server:
    image: redis:6.0.5-alpine
    container_name: redis-server
    command: redis-server --requirepass todovale
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - net-redis
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_interval: 5s

  redis-client:
    image: rediscommander/redis-commander:latest
    container_name: redis-client
    restart: unless-stopped
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
      REDIS_PASSWORD: todovale
    ports:
      - "8081:8081"
    networks:
      - net-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_interval: 5s
    depends_on:
      redis-server:
        condition: service_healthy

volumes:
  mysql-data:
    name: mysql-data
    driver: local
networks:
  net-mysql:
    name: net-mysql
    driver: bridge
  net-redis:
    name: net-redis
    driver: bridge
