### list users
GET  http://localhost:4000/user HTTP/1.1

### create user
POST  http://localhost:4000/user HTTP/1.1
content-type: application/json

{
    "name":"sergio", 
    "lastname": "hidalgo",
    "email":"correo@correo.com",
    "password": "12345", 
    "number": 825, 
    "country": "Perú", 
    "street": "Los Frutales",
    "roles": ["522d4f4c-7762-488f-8879-0431bbf6b449"]
}

### get user
GET http://localhost:4000/user/c1b2328c-fa69-4576-a5e6-5c77022097df HTTP/1.1

### update user
PUT http://localhost:4000/user/c1b2328c-fa69-4576-a5e6-5c77022097df HTTP/1.1
content-type: application/json

{
    "roles": ["522d4f4c-7762-488f-8879-0431bbf6b449", "793f2bb0-4449-4d46-b70b-c576b6f8e1f8"]
}

### users by page
GET http://localhost:4000/user/page/0/pageSize/20 HTTP/1.1

### delete user
DELETE http://localhost:4000/user/ac5e5ee0-c721-40ed-b4ff-1a59865818f1 HTTP/1.1

### users by role
GET http://localhost:4000/user/role/522d4f4c-7762-488f-8879-0431bbf6b449 HTTP/1.1