version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "8200:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: shidalgo
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: course
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - mysql-network

  mysql-client:
    image: phpmyadmin
    container_name: mysql-client
    environment:
      PMA_HOST: mysql-service
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    networks:
      - mysql-network

networks:
  mysql-network:
    name: mysql-network
    driver: bridge
